### ISSUE TITLE
Unable to set Steam Profile URL

### ISSUE THREAD

**Issue by ghost** [Tanweth/MySteam-Powered#12]
Hi, I run your plugin on my website, USAGamers.net, running on Mybb v1.6.12.  When I try to Integrate Steam with an account through Usercp and Modcp, I am redirected to a blank white page.  After that, the Steam account is never integrated with the user's account.

**Comment by Tanweth** [comment]
Hmm. Curious one. Have you tried switching to v1.1 (the version on the MyBB Mods site: http://mods.mybb.com/view/mysteam-powered)? Or, if you are running that, have you tried using the latest version on here? The method changed in v1.2, so if you have the issue on both v1.1 and v1.2.1, that would help me to pinpoint it.

**Comment by DammitStella** [comment]
Got the same bug as OP. After installing php5-curl it worked. You should add to your readme, that u need curl installed and activated for this plugin.

**Comment by Tanweth** [comment]
That makes sense, since the changed method in v1.2 now does use cURL. I'll add that to the readme in the next update. Since the OP hasn't responded, and another user has resolved the issue with a server configuration change, I'm closing this.
