### ISSUE TITLE
ISSUE - Clicking on Complete List

### ISSUE THREAD

**Issue by andydigi** [Tanweth/MySteam-Powered#2]
When clicking on the complete list link the site loads steam-list-complete.php but then 2 errors flag up:-

Warning [2] array_merge(): Argument #1 is not an array - Line: 47 - File: steam-list-complete.php PHP 5.4.25 (Linux)
/steam-list-complete.php    47  array_merge

Warning [2] Invalid argument supplied for foreach() - Line: 50 - File: steam-list-complete.php PHP 5.4.25 (Linux)
/steam-list-complete.php    50  errorHandler->error

No other issues can be found. Webserver is running PHP 5.4.25

**Comment by Tanweth** [comment]
_facepalm_ I'm quite appalled that I didn't notice that during testing. I can definitely reproduce the issue (it happens every time there isn't a member who is currently in-game), and it is a simple fix (indeed, I applied the fix to the main status list already). The fix will be included in v1.0.1, which should be released in the next day or two. Thanks for your report. :)
